name: calapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rushcal.jpg


  fonts:
    - family: PlaywriteVN
      fonts:
        - asset: lib/fonts/PlaywriteVN-Regular.ttf
        - asset: lib/fonts/PlaywriteVN-VariableFont_wght.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/rushcal.jpg"
